# Generated by Django 5.1 on 2025-11-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='CADRE DE CONCERTATION', max_length=200)),
                ('mois', models.CharField(max_length=50)),
                ('annee', models.IntegerField(default=2025)),
                ('resume_analytique', models.TextField(verbose_name='Résumé Analytique')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
