# Generated by Django 5.1 on 2025-11-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadreConcertation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='conclusion',
            field=models.TextField(default='', verbose_name='Conclusion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapport',
            name='etat_mise_en_oeuvre',
            field=models.TextField(default='', verbose_name='etat de mise en oeuvre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapport',
            name='presentation_du_budget',
            field=models.TextField(default='', verbose_name='presentation du budget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapport',
            name='situation',
            field=models.TextField(default='', verbose_name='situation'),
            preserve_default=False,
        ),
    ]
