# Generated by Django 5.1 on 2025-11-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadreConcertation', '0002_rapport_conclusion_rapport_etat_mise_en_oeuvre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='conclusion',
            field=models.TextField(null=True, verbose_name='Conclusion'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='etat_mise_en_oeuvre',
            field=models.TextField(null=True, verbose_name='etat de mise en oeuvre'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='introduction',
            field=models.TextField(null=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='presentation_du_budget',
            field=models.TextField(null=True, verbose_name='presentation du budget'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='resume_analytique',
            field=models.TextField(null=True, verbose_name='Résumé Analytique'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='situation',
            field=models.TextField(null=True, verbose_name='situation'),
        ),
    ]
