# Generated by Django 5.1 on 2025-11-23 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadreConcertation', '0004_alter_rapport_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rapport',
            options={'ordering': ['-annee', '-date_creation'], 'verbose_name': 'Rapport', 'verbose_name_plural': 'Rapports'},
        ),
    ]
