# Generated by Django 5.1 on 2025-01-13 18:30

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dated', models.BooleanField(default=True)),
                ('type', models.CharField(blank=True, choices=[("APPEL D'OFFRES OUVERT", "Appel d'offres ouvert"), ("APPEL D'OFFRES RESTREINT", "Appel d'offres restreint"), ('CONSULTATION INDIVIDUELLE', 'Consultation individuelle'), ('REGIE', 'Régie'), ('GRE A GRE', 'Gré à gré')], max_length=50, null=True, verbose_name="Type d'étape")),
                ('acteurs', models.CharField(blank=True, max_length=75, null=True)),
                ('delai', models.IntegerField(blank=True, null=True, verbose_name='delais fixe')),
                ('rang', models.IntegerField(blank=True, null=True, verbose_name='ordre de passage')),
                ('references', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEtapeContractualisation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_prevue', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('date_effective', models.DateField(blank=True, null=True, verbose_name='Date effective')),
                ('montant_prevu', models.FloatField(blank=True, null=True, verbose_name='Montant prévisionnel')),
                ('montant_reel', models.FloatField(blank=True, null=True, verbose_name='Montant réel')),
                ('taux_consomation', models.FloatField(blank=True, null=True, verbose_name='Taux de consommation')),
                ('observations', models.TextField(blank=True, null=True)),
                ('ecart_jours', models.IntegerField(blank=True, editable=False, null=True)),
                ('ecart_montant', models.FloatField(blank=True, editable=False, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('date_demarrage', models.DateField(blank=True, null=True, verbose_name='Date de démarrage')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('retard_message', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical etape contractualisation',
                'verbose_name_plural': 'historical etape contractualisations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Maturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_exec_physique', models.FloatField(blank=True, null=True, verbose_name="Taux d'execution physique")),
                ('taux_conso_delai', models.FloatField(blank=True, null=True, verbose_name='Taux de consommation des delais')),
                ('numero_marche', models.CharField(blank=True, null=True)),
                ('ingenieur_marche', models.CharField(blank=True, null=True)),
                ('chef_service_marche', models.CharField(blank=True, null=True)),
                ('prestataire', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'upload")),
                ('date_obtention', models.DateField(blank=True, null=True, verbose_name="Date d'obtention")),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointeContractualisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/contractualisation/', verbose_name='Fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'upload")),
                ('date_obtention', models.DateField(blank=True, null=True, verbose_name="Date d'obtention")),
            ],
        ),
        migrations.CreateModel(
            name='PPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_prestations', models.CharField(max_length=255)),
                ('montant_previsionnel', models.FloatField()),
                ('source_financement', models.CharField(max_length=255)),
                ('autorite_contractante', models.CharField(max_length=255)),
                ('mode_consultation_solicite', models.CharField(max_length=255)),
                ('procedure', models.CharField(max_length=255)),
                ('saisine_ac', models.DateField()),
                ('saisine_cpm', models.DateField()),
                ('examen_dao_cpm', models.DateField()),
                ('saisine_cccm_dao', models.DateField()),
                ('avis_cccm_dao', models.CharField(max_length=255)),
                ('non_objection_bf_1', models.CharField(max_length=255)),
                ('date_publication_ao', models.DateField()),
                ('depouillement_offres', models.DateField()),
                ('analyse_offres_techniques', models.DateField()),
                ('examen_rapport_offres_techniques', models.DateField()),
                ('non_objection_bf_2', models.CharField(max_length=255)),
                ('ouverture_offres_financieres', models.DateField()),
                ('analyse_offres_financieres_synthese', models.DateField()),
                ('proposition_attribution_cpm', models.CharField(max_length=255)),
                ('saisine_cccm_attribution', models.DateField()),
                ('avis_cccm_attribution', models.CharField(max_length=255)),
                ('non_objection_bf_3', models.CharField(max_length=255)),
                ('publication_resultats', models.DateField()),
                ('notification_decision_attribution', models.DateField()),
                ('preparation_projet_marche', models.DateField()),
                ('saisine_cpm_marche', models.DateField()),
                ('examen_projet_marche', models.DateField()),
                ('saisine_cccm_marche', models.DateField()),
                ('avis_cccm_projet_marche_gg', models.CharField(max_length=255)),
                ('non_objection_bf_4', models.CharField(max_length=255)),
                ('date_signature_marche', models.DateField()),
                ('notification_marche', models.DateField()),
                ('demarrage_prestations', models.DateField()),
                ('reception_provisoire', models.DateField()),
                ('reception_definitive', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EtapeContractualisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('date_effective', models.DateField(blank=True, null=True, verbose_name='Date effective')),
                ('montant_prevu', models.FloatField(blank=True, null=True, verbose_name='Montant prévisionnel')),
                ('montant_reel', models.FloatField(blank=True, null=True, verbose_name='Montant réel')),
                ('taux_consomation', models.FloatField(blank=True, null=True, verbose_name='Taux de consommation')),
                ('observations', models.TextField(blank=True, null=True)),
                ('ecart_jours', models.IntegerField(blank=True, editable=False, null=True)),
                ('ecart_montant', models.FloatField(blank=True, editable=False, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('date_demarrage', models.DateField(blank=True, null=True, verbose_name='Date de démarrage')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('retard_message', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etape', to='contractualisation.etape')),
            ],
        ),
    ]
