# Generated by Django 5.1 on 2024-10-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapecontractualisation',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaletapecontractualisation',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
