# Generated by Django 5.1 on 2025-01-24 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0003_etapecontractualisation_date_saisine_and_more'),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maturation',
            name='tache',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setting.tache'),
        ),
    ]
