# Generated by Django 5.1 on 2024-10-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0003_etape_dated_etapecontractualisation_ecart_montant_and_more'),
        ('setting', '0015_historicaltache_latitude_historicaltache_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapecontractualisation',
            name='tache',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projet', to='setting.tache'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaletapecontractualisation',
            name='tache',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setting.tache'),
        ),
    ]
