# Generated by Django 5.1 on 2025-01-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0004_alter_maturation_tache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maturation',
            old_name='prestataire',
            new_name='nom_prestataire',
        ),
        migrations.AddField(
            model_name='etapecontractualisation',
            name='delais_execution',
            field=models.IntegerField(blank=True, null=True, verbose_name="Delais d'execution"),
        ),
        migrations.AddField(
            model_name='historicaletapecontractualisation',
            name='delais_execution',
            field=models.IntegerField(blank=True, null=True, verbose_name="Delais d'execution"),
        ),
        migrations.AddField(
            model_name='maturation',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de constat'),
        ),
        migrations.AddField(
            model_name='maturation',
            name='niu_prestataire',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maturation',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maturation',
            name='taux_exec_financier',
            field=models.FloatField(blank=True, null=True, verbose_name="Taux d'execution financier"),
        ),
    ]
