# Generated by Django 5.1 on 2024-11-28 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0004_etapecontractualisation_tache_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapecontractualisation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='historicaletapecontractualisation',
            name='document',
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('date_obtention', models.DateField(blank=True, null=True, verbose_name="Date d'obtention")),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='contractualisation.etape')),
            ],
        ),
    ]
