# Generated by Django 5.1 on 2025-01-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0005_rename_prestataire_maturation_nom_prestataire_and_more'),
        ('setting', '0002_historicaltache_status_tache_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maturation',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.tache'),
        ),
    ]
