# Generated by Django 5.1 on 2024-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0006_alter_piecejointe_date_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecejointe',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fichier'),
        ),
    ]
