# Generated by Django 5.1 on 2025-01-28 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0006_alter_maturation_tache'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointeMaturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/maturation/', verbose_name='Fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'upload")),
                ('maturation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='contractualisation.maturation')),
            ],
        ),
    ]
