# Generated by Django 5.1 on 2024-12-04 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0008_jpm_current_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointeContractualisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/contractualisation/', verbose_name='Fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'upload")),
                ('date_obtention', models.DateField(blank=True, null=True, verbose_name="Date d'obtention")),
                ('etape_contractualisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='contractualisation.etapecontractualisation')),
            ],
        ),
    ]
