# Generated by Django 5.1 on 2024-12-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0009_piecejointecontractualisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='etape',
            name='type',
            field=models.CharField(choices=[("APPEL D'OFFRES OUVERT", "Appel d'offres ouvert"), ("APPEL D'OFFRES RESTREINT", "Appel d'offres restreint"), ('CONSULTATION INDIVIDUELLE', 'Consultation individuelle'), ('REGIE', 'Régie'), ('GRE A GRE', 'Gré à gré')], default="APPEL D'OFFRES OUVERT", max_length=50, verbose_name="Type d'étape"),
        ),
    ]
