# Generated by Django 5.1 on 2024-12-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0011_jpm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='etape',
            name='acteurs',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
