# Generated by Django 5.1 on 2024-12-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0012_etape_acteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapecontractualisation',
            name='date_demarrage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de démarrage'),
        ),
        migrations.AddField(
            model_name='etapecontractualisation',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='historicaletapecontractualisation',
            name='date_demarrage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de démarrage'),
        ),
        migrations.AddField(
            model_name='historicaletapecontractualisation',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
    ]
