# Generated by Django 5.1 on 2024-12-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0013_etapecontractualisation_date_demarrage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapecontractualisation',
            name='taux_consomation',
            field=models.FloatField(blank=True, null=True, verbose_name='Taux de consommation'),
        ),
        migrations.AlterField(
            model_name='historicaletapecontractualisation',
            name='taux_consomation',
            field=models.FloatField(blank=True, null=True, verbose_name='Taux de consommation'),
        ),
    ]
