# Generated by Django 5.1 on 2024-12-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0014_alter_etapecontractualisation_taux_consomation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JPM',
        ),
    ]
