# Generated by Django 5.1 on 2024-12-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0015_delete_jpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='etape',
            name='delai',
            field=models.IntegerField(blank=True, null=True, verbose_name='delais fixe'),
        ),
        migrations.AddField(
            model_name='etape',
            name='rang',
            field=models.IntegerField(blank=True, null=True, verbose_name='ordre de passage'),
        ),
        migrations.AddField(
            model_name='etape',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
