# Generated by Django 5.1 on 2024-12-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0016_etape_delai_etape_rang_etape_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapecontractualisation',
            name='etape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etape', to='contractualisation.etape'),
        ),
    ]
