# Generated by Django 5.1 on 2024-12-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0017_alter_etapecontractualisation_etape'),
        ('setting', '0016_historicaltache_current_step_historicaltache_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='etapecontractualisation',
            constraint=models.UniqueConstraint(fields=('tache', 'etape'), name='unique_tache_etape'),
        ),
    ]
