# Generated by Django 5.1 on 2024-12-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0019_etapecontractualisation_chef_service_marche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapecontractualisation',
            name='retard_message',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaletapecontractualisation',
            name='retard_message',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
