# Generated by Django 5.1 on 2025-01-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0020_etapecontractualisation_retard_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etape',
            name='type',
            field=models.CharField(blank=True, choices=[("APPEL D'OFFRES OUVERT", "Appel d'offres ouvert"), ("APPEL D'OFFRES RESTREINT", "Appel d'offres restreint"), ('CONSULTATION INDIVIDUELLE', 'Consultation individuelle'), ('REGIE', 'Régie'), ('GRE A GRE', 'Gré à gré')], max_length=50, null=True, verbose_name="Type d'étape"),
        ),
    ]
