# Generated by Django 5.1 on 2025-01-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0021_alter_etape_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapecontractualisation',
            name='date_demarrage',
            field=models.DateField(blank=True, null=True, verbose_name='Date de démarrage'),
        ),
        migrations.AlterField(
            model_name='etapecontractualisation',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='historicaletapecontractualisation',
            name='date_demarrage',
            field=models.DateField(blank=True, null=True, verbose_name='Date de démarrage'),
        ),
        migrations.AlterField(
            model_name='historicaletapecontractualisation',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
    ]
