# Generated by Django 5.1 on 2025-01-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0022_alter_etapecontractualisation_date_demarrage_and_more'),
        ('setting', '0022_historicaltache_contractualisation_termine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapecontractualisation',
            name='chef_service_marche',
        ),
        migrations.RemoveField(
            model_name='etapecontractualisation',
            name='ingenieur_marche',
        ),
        migrations.RemoveField(
            model_name='etapecontractualisation',
            name='numero_marche',
        ),
        migrations.RemoveField(
            model_name='etapecontractualisation',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='etapecontractualisation',
            name='taux_exec_physique',
        ),
        migrations.RemoveField(
            model_name='historicaletapecontractualisation',
            name='chef_service_marche',
        ),
        migrations.RemoveField(
            model_name='historicaletapecontractualisation',
            name='ingenieur_marche',
        ),
        migrations.RemoveField(
            model_name='historicaletapecontractualisation',
            name='numero_marche',
        ),
        migrations.RemoveField(
            model_name='historicaletapecontractualisation',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='historicaletapecontractualisation',
            name='taux_exec_physique',
        ),
        migrations.CreateModel(
            name='Maturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_exec_physique', models.FloatField(blank=True, null=True, verbose_name="Taux d'execution physique")),
                ('taux_conso_delai', models.FloatField(blank=True, null=True, verbose_name='Taux de consommation des delais')),
                ('numero_marche', models.CharField(blank=True, null=True)),
                ('ingenieur_marche', models.CharField(blank=True, null=True)),
                ('chef_service_marche', models.CharField(blank=True, null=True)),
                ('prestataire', models.CharField(blank=True, null=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.tache')),
            ],
        ),
    ]
