# Generated by Django 5.1 on 2025-09-24 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('bip_followup', 'Cadre de Concertation BIP'), ('other', 'Autre')], default='bip_followup', max_length=50)),
                ('month', models.CharField(max_length=7)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('physical_execution_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document_type', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BudgetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
                ('provision', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('physical_rate_june', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('physical_rate_july', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('engagement_rate_june', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('engagement_rate_july', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_components', to='reporting.concertationdocument')),
            ],
            options={
                'ordering': ['-provision'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('cover', 'Page de couverture'), ('summary', 'Sommaire'), ('analytical_summary', 'Résumé analytique'), ('introduction', 'Introduction'), ('recommendations', 'Recommandations'), ('budget_presentation', 'Présentation du budget'), ('execution_status', "État d'exécution"), ('annexes', 'Annexes'), ('custom', 'Section personnalisée')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reporting.concertationdocument')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
