# Generated by Django 5.1 on 2025-09-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertationdocument',
            name='created_by',
        ),
    ]
