# Generated by Django 5.1 on 2025-09-25 01:25

import django.db.models.deletion
import reporting.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_remove_concertationdocument_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertationdocument',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AddField(
            model_name='concertationdocument',
            name='auto_generate_toc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentsection',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentsection',
            name='last_saved',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='documentsection',
            unique_together={('document', 'section_type')},
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reporting.models.document_image_path)),
                ('original_name', models.CharField(max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reporting.concertationdocument')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
