# Generated by Django 3.2.5 on 2024-08-12 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('objectif', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('objectif', models.TextField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='setting.action')),
            ],
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EtapeExecutionGlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('dateimport', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModeGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('objectif', models.TextField()),
                ('cout_tot', models.FloatField()),
                ('numero_marche', models.CharField(blank=True, max_length=255, null=True)),
                ('montant_previsionnel', models.FloatField(blank=True, null=True)),
                ('adjudicataire', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_notification', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_ods', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_pv', models.CharField(blank=True, max_length=255, null=True)),
                ('montant_reel', models.FloatField(blank=True, null=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='setting.activite')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('objectif', models.TextField()),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='setting.chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='NatureDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type_ressources', models.ManyToManyField(related_name='natures_depense', to='setting.TypeRessource')),
            ],
        ),
        migrations.CreateModel(
            name='EstExecuteePour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_ae_init', models.FloatField()),
                ('montant_cp_init', models.FloatField()),
                ('montant_ae_rev', models.FloatField()),
                ('montant_cp_rev', models.FloatField()),
                ('dateimport', models.DateField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.action')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.activite')),
                ('etape_execution_glob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.etapeexecutionglob')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.exercice')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.programme')),
            ],
        ),
        migrations.CreateModel(
            name='EstExecuteeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_ae_init', models.FloatField()),
                ('montant_cp_init', models.FloatField()),
                ('montant_ae_rev', models.FloatField()),
                ('montant_cp_rev', models.FloatField()),
                ('dateimport', models.DateField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.action')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.activite')),
                ('etape_execution_glob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.etapeexecutionglob')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.exercice')),
                ('groupe_depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.groupedepense')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.operation')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.programme')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='est_executee_operations', to='setting.tache')),
            ],
        ),
        migrations.CreateModel(
            name='EstExecuteeModeGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_ae_init', models.FloatField()),
                ('montant_cp_init', models.FloatField()),
                ('montant_ae_rev', models.FloatField()),
                ('montant_cp_rev', models.FloatField()),
                ('dateimport', models.DateField()),
                ('etape_execution_glob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.etapeexecutionglob')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.exercice')),
                ('mode_gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.modegestion')),
            ],
        ),
        migrations.CreateModel(
            name='EstExecuteeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_ae_init', models.FloatField()),
                ('montant_cp_init', models.FloatField()),
                ('montant_ae_rev', models.FloatField()),
                ('montant_cp_rev', models.FloatField()),
                ('dateimport', models.DateField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.action')),
                ('etape_execution_glob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.etapeexecutionglob')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.exercice')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.programme')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='setting.programme'),
        ),
    ]
