# Generated by Django 5.1 on 2025-01-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltache',
            name='status',
            field=models.CharField(blank=True, choices=[('EN COURS', "En cours d'execution"), ('EN ARRET', 'En arret'), ('RECEPTIONNE', 'Receptionne')], max_length=50, null=True, verbose_name='Status de la tache'),
        ),
        migrations.AddField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('EN COURS', "En cours d'execution"), ('EN ARRET', 'En arret'), ('RECEPTIONNE', 'Receptionne')], max_length=50, null=True, verbose_name='Status de la tache'),
        ),
    ]
