# Generated by Django 5.1 on 2025-01-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_historicaltache_status_tache_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltache',
            name='date_forclusion',
            field=models.DateField(blank=True, null=True, verbose_name='Date de forclusion personnalisée'),
        ),
        migrations.AddField(
            model_name='historicaltache',
            name='etat_de_forclusion',
            field=models.CharField(blank=True, choices=[('FORCLOS 15 OCTOBRE', 'Forclos 15 octobre'), ('FORCLOS 15 NOVEMBRE', 'Forclos 15 novembre'), ('FORCLOS 31 DECEMBRE', 'Forclos 31 décembre'), ('CUSTOM', 'Date personnalisée')], max_length=50, null=True, verbose_name='État de forclusion'),
        ),
        migrations.AddField(
            model_name='tache',
            name='date_forclusion',
            field=models.DateField(blank=True, null=True, verbose_name='Date de forclusion personnalisée'),
        ),
        migrations.AddField(
            model_name='tache',
            name='etat_de_forclusion',
            field=models.CharField(blank=True, choices=[('FORCLOS 15 OCTOBRE', 'Forclos 15 octobre'), ('FORCLOS 15 NOVEMBRE', 'Forclos 15 novembre'), ('FORCLOS 31 DECEMBRE', 'Forclos 31 décembre'), ('CUSTOM', 'Date personnalisée')], max_length=50, null=True, verbose_name='État de forclusion'),
        ),
    ]
