# Generated by Django 5.1 on 2025-02-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_historicaltache_date_forclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltache',
            name='delais_execution',
            field=models.IntegerField(blank=True, null=True, verbose_name="Delais d'execution"),
        ),
        migrations.AddField(
            model_name='tache',
            name='delais_execution',
            field=models.IntegerField(blank=True, null=True, verbose_name="Delais d'execution"),
        ),
    ]
