# Generated by Django 5.1 on 2024-08-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_etapecontractualisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcommune',
            name='arrondissement',
        ),
        migrations.RemoveField(
            model_name='historicalcommune',
            name='history_user',
        ),
        migrations.RenameField(
            model_name='arrondissement',
            old_name='name_fr',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='departement',
            old_name='name_fr',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='historicalarrondissement',
            old_name='name_fr',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='historicaldepartement',
            old_name='name_fr',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='arrondissement',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalarrondissement',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicaldepartement',
            name='name_en',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='HistoricalCommune',
        ),
    ]
