# Generated by Django 5.1 on 2025-02-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_historicaltache_delais_execution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltache',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='groupe',
        ),
        migrations.AddField(
            model_name='historicaltache',
            name='type_execution',
            field=models.CharField(blank=True, choices=[('FCPDR', 'Fond de contrepartie depense reelles'), ('SUBV', 'Transferts et subventions'), ('GC', 'Gestion Centrale')], max_length=50, null=True, verbose_name="Type d'execution"),
        ),
        migrations.AddField(
            model_name='tache',
            name='type_execution',
            field=models.CharField(blank=True, choices=[('FCPDR', 'Fond de contrepartie depense reelles'), ('SUBV', 'Transferts et subventions'), ('GC', 'Gestion Centrale')], max_length=50, null=True, verbose_name="Type d'execution"),
        ),
    ]
