# Generated by Django 5.1 on 2024-08-18 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_remove_historicalcommune_arrondissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estexecuteeaction',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estexecuteeaction',
            name='etape_execution_glob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.etapeexecutionglob'),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteeaction',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
