# Generated by Django 5.1 on 2025-02-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_remove_historicaltache_groupe_remove_tache_groupe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltache',
            name='type_execution',
            field=models.CharField(blank=True, choices=[('FCPDR', 'Fond de contrepartie depense reelles'), ('SUBV', 'Transferts et subventions'), ('PIISAH', 'Piisah'), ('PLANUT', 'Planut'), ('PLURIANNUEL', 'Pluriannuel')], max_length=50, null=True, verbose_name="Type d'execution"),
        ),
        migrations.AlterField(
            model_name='tache',
            name='type_execution',
            field=models.CharField(blank=True, choices=[('FCPDR', 'Fond de contrepartie depense reelles'), ('SUBV', 'Transferts et subventions'), ('PIISAH', 'Piisah'), ('PLANUT', 'Planut'), ('PLURIANNUEL', 'Pluriannuel')], max_length=50, null=True, verbose_name="Type d'execution"),
        ),
    ]
