# Generated by Django 5.1 on 2025-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_historicaltache_type_execution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltache',
            name='type_execution',
            field=models.CharField(blank=True, choices=[('FCPDR', 'Fond de contrepartie depense reelles'), ('ETAPUB', 'Etablissement publiques'), ('STRUCTRAT', 'Structures rattachées'), ('PIISAH', 'Piisah'), ('PLANUS', 'Planus'), ('PLURIANNUEL', 'Pluriannuel')], max_length=50, null=True, verbose_name="Type d'execution"),
        ),
        migrations.AlterField(
            model_name='tache',
            name='type_execution',
            field=models.CharField(blank=True, choices=[('FCPDR', 'Fond de contrepartie depense reelles'), ('ETAPUB', 'Etablissement publiques'), ('STRUCTRAT', 'Structures rattachées'), ('PIISAH', 'Piisah'), ('PLANUS', 'Planus'), ('PLURIANNUEL', 'Pluriannuel')], max_length=50, null=True, verbose_name="Type d'execution"),
        ),
    ]
