# Generated by Django 5.1 on 2024-08-18 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_estexecuteeaction_dateimport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estexecuteefcpdr',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estexecuteefcptdd',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estexecuteegcautres',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estexecuteegcsub',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estexecuteemodegestion',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estexecuteeoperationfdcdr',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteefcpdr',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteefcptdd',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteegcautres',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteegcsub',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteemodegestion',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteeoperationfdcdr',
            name='dateimport',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
