# Generated by Django 5.1 on 2025-06-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_alter_historicaltache_type_execution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltache',
            name='arrondissement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setting.arrondissement'),
        ),
        migrations.AddField(
            model_name='tache',
            name='arrondissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.arrondissement'),
        ),
    ]
