# Generated by Django 5.1 on 2024-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_remove_estexecuteefcpdr_etape_execution_glob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnaturedepense',
            name='code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturedepense',
            name='code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
