# Generated by Django 5.1 on 2024-08-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_historicalmodegestion_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnaturedepense',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='naturedepense',
            name='mode',
        ),
    ]
