# Generated by Django 5.1 on 2024-08-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_remove_historicalnaturedepense_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnaturedepense',
            name='groupe',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setting.groupedepense'),
        ),
        migrations.AddField(
            model_name='naturedepense',
            name='groupe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='setting.groupedepense'),
            preserve_default=False,
        ),
    ]
