# Generated by Django 5.1 on 2024-10-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0013_groupe_historicaloperation_code_operation_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EtapeContractualisation',
        ),
        migrations.DeleteModel(
            name='HistoricalEtapeContractualisation',
        ),
    ]
