# Generated by Django 5.1 on 2024-12-14 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractualisation', '0015_delete_jpm'),
        ('setting', '0015_historicaltache_latitude_historicaltache_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltache',
            name='current_step',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contractualisation.etapecontractualisation'),
        ),
        migrations.AddField(
            model_name='historicaltache',
            name='type',
            field=models.CharField(choices=[("APPEL D'OFFRES OUVERT", "Appel d'offres ouvert"), ("APPEL D'OFFRES RESTREINT", "Appel d'offres restreint"), ('CONSULTATION INDIVIDUELLE', 'Consultation individuelle'), ('REGIE', 'Régie'), ('GRE A GRE', 'Gré à gré')], default="APPEL D'OFFRES OUVERT", max_length=50, verbose_name="Type d'étape"),
        ),
        migrations.AddField(
            model_name='tache',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_step', to='contractualisation.etapecontractualisation'),
        ),
        migrations.AddField(
            model_name='tache',
            name='type',
            field=models.CharField(choices=[("APPEL D'OFFRES OUVERT", "Appel d'offres ouvert"), ("APPEL D'OFFRES RESTREINT", "Appel d'offres restreint"), ('CONSULTATION INDIVIDUELLE', 'Consultation individuelle'), ('REGIE', 'Régie'), ('GRE A GRE', 'Gré à gré')], default="APPEL D'OFFRES OUVERT", max_length=50, verbose_name="Type d'étape"),
        ),
    ]
