# Generated by Django 5.1 on 2024-12-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0016_historicaltache_current_step_historicaltache_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltache',
            name='objectif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='objectif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
