# Generated by Django 5.1 on 2025-01-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0017_alter_historicaltache_objectif_alter_tache_objectif'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltache',
            name='groupe',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setting.groupe'),
        ),
        migrations.AddField(
            model_name='tache',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.groupe'),
        ),
    ]
