# Generated by Django 5.1 on 2025-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0018_historicaltache_groupe_tache_groupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='tache',
        ),
        migrations.AddField(
            model_name='historicaltache',
            name='montant_operation_restant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='montant_operation_restant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalOperation',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
