# Generated by Django 5.1 on 2025-01-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0019_remove_operation_tache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='exercices',
            field=models.ManyToManyField(related_name='taches', to='setting.exercice'),
        ),
    ]
