# Generated by Django 5.1 on 2025-01-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0020_tache_exercices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltache',
            name='type',
            field=models.CharField(blank=True, choices=[("APPEL D'OFFRES OUVERT", "Appel d'offres ouvert"), ("APPEL D'OFFRES RESTREINT", "Appel d'offres restreint"), ('CONSULTATION INDIVIDUELLE', 'Consultation individuelle'), ('REGIE', 'Régie'), ('GRE A GRE', 'Gré à gré')], max_length=50, null=True, verbose_name="Type d'étape"),
        ),
        migrations.AlterField(
            model_name='tache',
            name='type',
            field=models.CharField(blank=True, choices=[("APPEL D'OFFRES OUVERT", "Appel d'offres ouvert"), ("APPEL D'OFFRES RESTREINT", "Appel d'offres restreint"), ('CONSULTATION INDIVIDUELLE', 'Consultation individuelle'), ('REGIE', 'Régie'), ('GRE A GRE', 'Gré à gré')], max_length=50, null=True, verbose_name="Type d'étape"),
        ),
    ]
