# Generated by Django 5.1 on 2025-01-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0021_alter_historicaltache_type_alter_tache_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltache',
            name='contractualisation_termine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tache',
            name='contractualisation_termine',
            field=models.BooleanField(default=False),
        ),
    ]
