# Generated by Django 5.1 on 2025-02-07 15:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('FCPDR', 'Fond de contrepartie depense reelles'), ('SUBV', 'Transferts et subventions')], max_length=50, null=True, verbose_name="Type d'étape")),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='consommation',
            old_name='montant',
            new_name='montant_engage',
        ),
        migrations.RenameField(
            model_name='historicalconsommation',
            old_name='montant',
            new_name='montant_engage',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='chef_service',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='date_situation',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='ingenieur_marche',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='numero_marche',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='pourcentage_exec_physique',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='situation_contract',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='chef_service',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='date_situation',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='ingenieur_marche',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='numero_marche',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='pourcentage_exec_physique',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='prestataire',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='situation_contract',
        ),
        migrations.AddField(
            model_name='consommation',
            name='chef_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consommation',
            name='date_situation',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='consommation',
            name='delai_exec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consommation',
            name='ingenieur_marche',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consommation',
            name='montant_contrat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consommation',
            name='numero_marche',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consommation',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consommation',
            name='pourcentage_exec_physique',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consommation',
            name='prestataire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consommation',
            name='situation_contract',
            field=models.CharField(choices=[('BC:Non executé', 'BC:Non executé'), ('BC:Exec. en cours', 'BC:Exec. en cours'), ('BC:Executé', 'BC:Executé'), ('Marché:Gré-a-Gré,Accord MINMAP attendu', 'Marché:Gré-a-Gré,Accord MINMAP attendu'), ('Marché:ASMI/AMI en cours', 'Marché:ASMI/AMI en cours'), ('Marché:DAO non transmis', 'Marché:DAO non transmis'), ('Marché:DAO en CCC', 'Marché:DAO en CCC'), ('Marché:DAO transmis en CIPM', 'Marché:DAO transmis en CIPM'), ('Marché:AO lancé', 'Marché:AO lancé'), ('Marché:AO infructueux', 'Marché:AO infructueux'), ('Marché:Gré-a-Gré,proc. en cours', 'Marché:Gré-a-Gré,proc. en cours'), ('Marché:Analyse offres en cours', 'Marché:Analyse offres en cours'), ('Marché:Prop. attrib. en CCC', 'Marché:Prop. attrib. en CCC'), ('Marché:Attribué', 'Marché:Attribué'), ('Marché:Gré-a-Gré,proj. Marché en CCC', 'Marché:Gré-a-Gré,proj. Marché en CCC'), ('Marché:Signé', 'Marché:Signé'), ('Marché:OS Dem. trav. notifié', 'Marché:OS Dem. trav. notifié'), ('Marché:OS Susp. trav. notifié', 'Marché:OS Susp. trav. notifié'), ('Marché:Avenant en cours', 'Marché:Avenant en cours'), ('Marché:receptionné', 'Marché:receptionné'), ('Marché pluriannuel signé avant 2024', 'Marché pluriannuel signé avant 2024'), ('Marché:chantier abandonné', 'Marché:chantier abandonné'), ('Marché:resilié', 'Marché:resilié'), ('Marché spécial:non signé', 'Marché spécial:non signé'), ('Marché spécial:signé', 'Marché spécial:signé'), ('Marché spécial:receptionné', 'Marché spécial:receptionné'), ('Régie:Accord MINMAP attendu', 'Régie:Accord MINMAP attendu'), ('Régie:Exec. en cours', 'Régie:Exec. en cours'), ('Régie:Exec. complete', 'Régie:Exec. complete'), ('Convention:signature en cours', 'Convention:signature en cours'), ('Convention:signée', 'Convention:signée'), ('Convention:Commande receptionnée', 'Convention:Commande receptionnée'), ('Arriérée:liasse incomplete', 'Arriérée:liasse incomplete'), ('Arriérée:liasse complete', 'Arriérée:liasse complete'), ('Autre Opération Fonct.:Non executé', 'Autre Opération Fonct.:Non executé'), ('Autre Opération Fonct.:Executé', 'Autre Opération Fonct.:Executé'), ('Dotation non repartie', 'Dotation non repartie')], default='BC:Non executé', max_length=300),
        ),
        migrations.AddField(
            model_name='historicalconsommation',
            name='chef_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalconsommation',
            name='date_situation',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicalconsommation',
            name='delai_exec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalconsommation',
            name='ingenieur_marche',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalconsommation',
            name='montant_contrat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalconsommation',
            name='numero_marche',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalconsommation',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalconsommation',
            name='pourcentage_exec_physique',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalconsommation',
            name='prestataire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalconsommation',
            name='situation_contract',
            field=models.CharField(choices=[('BC:Non executé', 'BC:Non executé'), ('BC:Exec. en cours', 'BC:Exec. en cours'), ('BC:Executé', 'BC:Executé'), ('Marché:Gré-a-Gré,Accord MINMAP attendu', 'Marché:Gré-a-Gré,Accord MINMAP attendu'), ('Marché:ASMI/AMI en cours', 'Marché:ASMI/AMI en cours'), ('Marché:DAO non transmis', 'Marché:DAO non transmis'), ('Marché:DAO en CCC', 'Marché:DAO en CCC'), ('Marché:DAO transmis en CIPM', 'Marché:DAO transmis en CIPM'), ('Marché:AO lancé', 'Marché:AO lancé'), ('Marché:AO infructueux', 'Marché:AO infructueux'), ('Marché:Gré-a-Gré,proc. en cours', 'Marché:Gré-a-Gré,proc. en cours'), ('Marché:Analyse offres en cours', 'Marché:Analyse offres en cours'), ('Marché:Prop. attrib. en CCC', 'Marché:Prop. attrib. en CCC'), ('Marché:Attribué', 'Marché:Attribué'), ('Marché:Gré-a-Gré,proj. Marché en CCC', 'Marché:Gré-a-Gré,proj. Marché en CCC'), ('Marché:Signé', 'Marché:Signé'), ('Marché:OS Dem. trav. notifié', 'Marché:OS Dem. trav. notifié'), ('Marché:OS Susp. trav. notifié', 'Marché:OS Susp. trav. notifié'), ('Marché:Avenant en cours', 'Marché:Avenant en cours'), ('Marché:receptionné', 'Marché:receptionné'), ('Marché pluriannuel signé avant 2024', 'Marché pluriannuel signé avant 2024'), ('Marché:chantier abandonné', 'Marché:chantier abandonné'), ('Marché:resilié', 'Marché:resilié'), ('Marché spécial:non signé', 'Marché spécial:non signé'), ('Marché spécial:signé', 'Marché spécial:signé'), ('Marché spécial:receptionné', 'Marché spécial:receptionné'), ('Régie:Accord MINMAP attendu', 'Régie:Accord MINMAP attendu'), ('Régie:Exec. en cours', 'Régie:Exec. en cours'), ('Régie:Exec. complete', 'Régie:Exec. complete'), ('Convention:signature en cours', 'Convention:signature en cours'), ('Convention:signée', 'Convention:signée'), ('Convention:Commande receptionnée', 'Convention:Commande receptionnée'), ('Arriérée:liasse incomplete', 'Arriérée:liasse incomplete'), ('Arriérée:liasse complete', 'Arriérée:liasse complete'), ('Autre Opération Fonct.:Non executé', 'Autre Opération Fonct.:Non executé'), ('Autre Opération Fonct.:Executé', 'Autre Opération Fonct.:Executé'), ('Dotation non repartie', 'Dotation non repartie')], default='BC:Non executé', max_length=300),
        ),
        migrations.AddField(
            model_name='historicaloperation',
            name='title_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaloperation',
            name='title_fr',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='title_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='title_fr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaloperation',
            name='groupe',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='execution.groupe'),
        ),
        migrations.AddField(
            model_name='operation',
            name='groupe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='execution.groupe'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoricalGroupe',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('FCPDR', 'Fond de contrepartie depense reelles'), ('SUBV', 'Transferts et subventions')], max_length=50, null=True, verbose_name="Type d'étape")),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical groupe',
                'verbose_name_plural': 'historical groupes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
