# Generated by Django 5.1 on 2025-02-11 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_alter_operation_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='execution.groupe'),
        ),
    ]
