# Generated by Django 5.1 on 2024-09-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_rename_montant_ae_init_estexecuteeoperationfdcdr_montant_ae_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estexecuteeaction',
            name='liquidation',
        ),
        migrations.RemoveField(
            model_name='estexecuteefcpdr',
            name='liquidation',
        ),
        migrations.RemoveField(
            model_name='estexecuteefcptdd',
            name='liquidation',
        ),
        migrations.RemoveField(
            model_name='estexecuteegcautres',
            name='liquidation',
        ),
        migrations.RemoveField(
            model_name='estexecuteegcsub',
            name='liquidation',
        ),
        migrations.RemoveField(
            model_name='estexecuteemodegestion',
            name='liquidation',
        ),
        migrations.RemoveField(
            model_name='historicalestexecuteeaction',
            name='liquidation',
        ),
        migrations.RemoveField(
            model_name='historicalestexecuteefcpdr',
            name='liquidation',
        ),
        migrations.RemoveField(
            model_name='historicalestexecuteefcptdd',
            name='liquidation',
        ),
        migrations.RemoveField(
            model_name='historicalestexecuteegcautres',
            name='liquidation',
        ),
        migrations.RemoveField(
            model_name='historicalestexecuteegcsub',
            name='liquidation',
        ),
        migrations.RemoveField(
            model_name='historicalestexecuteemodegestion',
            name='liquidation',
        ),
    ]
