# Generated by Django 5.1 on 2025-02-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_alter_operation_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperation',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
