# Generated by Django 5.1 on 2024-09-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_remove_estexecuteeaction_liquidation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estexecuteefcpdr',
            name='gc_category_ressource',
            field=models.CharField(default='RAS', max_length=45),
        ),
        migrations.AlterField(
            model_name='estexecuteegcautres',
            name='gc_category_ressource',
            field=models.CharField(default='RAS', max_length=45),
        ),
        migrations.AlterField(
            model_name='estexecuteegcsub',
            name='gc_category_ressource',
            field=models.CharField(default='RAS', max_length=45),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteefcpdr',
            name='gc_category_ressource',
            field=models.CharField(default='RAS', max_length=45),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteegcautres',
            name='gc_category_ressource',
            field=models.CharField(default='RAS', max_length=45),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteegcsub',
            name='gc_category_ressource',
            field=models.CharField(default='RAS', max_length=45),
        ),
    ]
