# Generated by Django 5.1 on 2025-02-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_remove_consommation_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='type',
            field=models.CharField(choices=[('FCPDR', 'Fond de contrepartie depense reelles'), ('SUBV', 'Transferts et subventions')], max_length=50, verbose_name="Type d'étape"),
        ),
        migrations.AlterField(
            model_name='historicalgroupe',
            name='type',
            field=models.CharField(choices=[('FCPDR', 'Fond de contrepartie depense reelles'), ('SUBV', 'Transferts et subventions')], max_length=50, verbose_name="Type d'étape"),
        ),
    ]
