# Generated by Django 5.1 on 2025-03-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0007_alter_groupe_type_alter_historicalgroupe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='report_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalconsommation',
            name='report_received',
            field=models.BooleanField(default=False),
        ),
    ]
