# Generated by Django 5.1 on 2025-03-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0008_consommation_report_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='type',
            field=models.CharField(choices=[('FCPDR', 'Fond de contrepartie depense reelles'), ('SUBV', 'Transferts et subventions')], max_length=50, verbose_name="Type de groupes d'operation"),
        ),
        migrations.AlterField(
            model_name='historicalgroupe',
            name='type',
            field=models.CharField(choices=[('FCPDR', 'Fond de contrepartie depense reelles'), ('SUBV', 'Transferts et subventions')], max_length=50, verbose_name="Type de groupes d'operation"),
        ),
    ]
