# Generated by Django 5.1 on 2025-01-03 13:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0008_alter_estexecuteeaction_ressource_mobilise_and_more'),
        ('setting', '0019_remove_operation_tache_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOperation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('situation_contract', models.CharField(choices=[('BC:Non executé', 'BC:Non executé'), ('BC:Exec. en cours', 'BC:Exec. en cours'), ('BC:Executé', 'BC:Executé'), ('Marché:Gré-a-Gré,Accord MINMAP attendu', 'Marché:Gré-a-Gré,Accord MINMAP attendu'), ('Marché:ASMI/AMI en cours', 'Marché:ASMI/AMI en cours'), ('Marché:DAO non transmis', 'Marché:DAO non transmis'), ('Marché:DAO en CCC', 'Marché:DAO en CCC'), ('Marché:DAO transmis en CIPM', 'Marché:DAO transmis en CIPM'), ('Marché:AO lancé', 'Marché:AO lancé'), ('Marché:AO infructueux', 'Marché:AO infructueux'), ('Marché:Gré-a-Gré,proc. en cours', 'Marché:Gré-a-Gré,proc. en cours'), ('Marché:Analyse offres en cours', 'Marché:Analyse offres en cours'), ('Marché:Prop. attrib. en CCC', 'Marché:Prop. attrib. en CCC'), ('Marché:Attribué', 'Marché:Attribué'), ('Marché:Gré-a-Gré,proj. Marché en CCC', 'Marché:Gré-a-Gré,proj. Marché en CCC'), ('Marché:Signé', 'Marché:Signé'), ('Marché:OS Dem. trav. notifié', 'Marché:OS Dem. trav. notifié'), ('Marché:OS Susp. trav. notifié', 'Marché:OS Susp. trav. notifié'), ('Marché:Avenant en cours', 'Marché:Avenant en cours'), ('Marché:receptionné', 'Marché:receptionné'), ('Marché pluriannuel signé avant 2024', 'Marché pluriannuel signé avant 2024'), ('Marché:chantier abandonné', 'Marché:chantier abandonné'), ('Marché:resilié', 'Marché:resilié'), ('Marché spécial:non signé', 'Marché spécial:non signé'), ('Marché spécial:signé', 'Marché spécial:signé'), ('Marché spécial:receptionné', 'Marché spécial:receptionné'), ('Régie:Accord MINMAP attendu', 'Régie:Accord MINMAP attendu'), ('Régie:Exec. en cours', 'Régie:Exec. en cours'), ('Régie:Exec. complete', 'Régie:Exec. complete'), ('Convention:signature en cours', 'Convention:signature en cours'), ('Convention:signée', 'Convention:signée'), ('Convention:Commande receptionnée', 'Convention:Commande receptionnée'), ('Arriérée:liasse incomplete', 'Arriérée:liasse incomplete'), ('Arriérée:liasse complete', 'Arriérée:liasse complete'), ('Autre Opération Fonct.:Non executé', 'Autre Opération Fonct.:Non executé'), ('Autre Opération Fonct.:Executé', 'Autre Opération Fonct.:Executé'), ('Dotation non repartie', 'Dotation non repartie')], default='BC:Non executé', max_length=300)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('delai_exec', models.IntegerField(blank=True, null=True)),
                ('date_situation', models.DateTimeField()),
                ('montant_engage', models.FloatField(blank=True, null=True)),
                ('pourcentage_exec_physique', models.FloatField(blank=True, null=True)),
                ('numero_marche', models.CharField(blank=True, max_length=255, null=True)),
                ('prestataire', models.CharField(blank=True, max_length=255, null=True)),
                ('ingenieur_marche', models.CharField(blank=True, max_length=255, null=True)),
                ('chef_service', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tache', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='setting.tache')),
            ],
            options={
                'verbose_name': 'historical operation',
                'verbose_name_plural': 'historical operations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_contract', models.CharField(choices=[('BC:Non executé', 'BC:Non executé'), ('BC:Exec. en cours', 'BC:Exec. en cours'), ('BC:Executé', 'BC:Executé'), ('Marché:Gré-a-Gré,Accord MINMAP attendu', 'Marché:Gré-a-Gré,Accord MINMAP attendu'), ('Marché:ASMI/AMI en cours', 'Marché:ASMI/AMI en cours'), ('Marché:DAO non transmis', 'Marché:DAO non transmis'), ('Marché:DAO en CCC', 'Marché:DAO en CCC'), ('Marché:DAO transmis en CIPM', 'Marché:DAO transmis en CIPM'), ('Marché:AO lancé', 'Marché:AO lancé'), ('Marché:AO infructueux', 'Marché:AO infructueux'), ('Marché:Gré-a-Gré,proc. en cours', 'Marché:Gré-a-Gré,proc. en cours'), ('Marché:Analyse offres en cours', 'Marché:Analyse offres en cours'), ('Marché:Prop. attrib. en CCC', 'Marché:Prop. attrib. en CCC'), ('Marché:Attribué', 'Marché:Attribué'), ('Marché:Gré-a-Gré,proj. Marché en CCC', 'Marché:Gré-a-Gré,proj. Marché en CCC'), ('Marché:Signé', 'Marché:Signé'), ('Marché:OS Dem. trav. notifié', 'Marché:OS Dem. trav. notifié'), ('Marché:OS Susp. trav. notifié', 'Marché:OS Susp. trav. notifié'), ('Marché:Avenant en cours', 'Marché:Avenant en cours'), ('Marché:receptionné', 'Marché:receptionné'), ('Marché pluriannuel signé avant 2024', 'Marché pluriannuel signé avant 2024'), ('Marché:chantier abandonné', 'Marché:chantier abandonné'), ('Marché:resilié', 'Marché:resilié'), ('Marché spécial:non signé', 'Marché spécial:non signé'), ('Marché spécial:signé', 'Marché spécial:signé'), ('Marché spécial:receptionné', 'Marché spécial:receptionné'), ('Régie:Accord MINMAP attendu', 'Régie:Accord MINMAP attendu'), ('Régie:Exec. en cours', 'Régie:Exec. en cours'), ('Régie:Exec. complete', 'Régie:Exec. complete'), ('Convention:signature en cours', 'Convention:signature en cours'), ('Convention:signée', 'Convention:signée'), ('Convention:Commande receptionnée', 'Convention:Commande receptionnée'), ('Arriérée:liasse incomplete', 'Arriérée:liasse incomplete'), ('Arriérée:liasse complete', 'Arriérée:liasse complete'), ('Autre Opération Fonct.:Non executé', 'Autre Opération Fonct.:Non executé'), ('Autre Opération Fonct.:Executé', 'Autre Opération Fonct.:Executé'), ('Dotation non repartie', 'Dotation non repartie')], default='BC:Non executé', max_length=300)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('delai_exec', models.IntegerField(blank=True, null=True)),
                ('date_situation', models.DateTimeField()),
                ('montant_engage', models.FloatField(blank=True, null=True)),
                ('pourcentage_exec_physique', models.FloatField(blank=True, null=True)),
                ('numero_marche', models.CharField(blank=True, max_length=255, null=True)),
                ('prestataire', models.CharField(blank=True, max_length=255, null=True)),
                ('ingenieur_marche', models.CharField(blank=True, max_length=255, null=True)),
                ('chef_service', models.CharField(blank=True, max_length=255, null=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.tache')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalConsommation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('document', models.TextField(blank=True, max_length=100, null=True, verbose_name='Fichier')),
                ('montant', models.FloatField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='execution.operation')),
            ],
            options={
                'verbose_name': 'historical consommation',
                'verbose_name_plural': 'historical consommations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/consommations/', verbose_name='Fichier')),
                ('montant', models.FloatField(blank=True, null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execution.operation')),
            ],
        ),
    ]
