# Generated by Django 5.1 on 2025-04-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0009_alter_groupe_type_alter_historicalgroupe_type'),
        ('setting', '0006_alter_historicaltache_type_execution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='setting.tache'),
        ),
    ]
