# Generated by Django 5.1 on 2025-01-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0009_historicaloperation_operation_historicalconsommation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estexecuteefcpdr',
            name='date_demarrage_travaux',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estexecuteegcautres',
            name='date_demarrage_travaux',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estexecuteegcsub',
            name='date_demarrage_travaux',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estexecuteeoperationfdcdr',
            name='date_demarrage_travaux',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteefcpdr',
            name='date_demarrage_travaux',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteegcautres',
            name='date_demarrage_travaux',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteegcsub',
            name='date_demarrage_travaux',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalestexecuteeoperationfdcdr',
            name='date_demarrage_travaux',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicaloperation',
            name='date_situation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date_situation',
            field=models.DateField(),
        ),
    ]
